apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: ingress-namespace
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333